'use strict';

/**
 * Monte Carlo control experiment.
 *
 * Feeds the selection engine draws generated by a fair random number generator —
 * a game with, by construction, zero exploitable structure — and reports how
 * often it declares a group "stronger than chance".
 *
 * This is the regression test that matters most. An earlier version of this
 * project ranked candidates by their frequency in the same window they were
 * mined from, and under this exact control it flagged a significant group in 14
 * of 15 runs. A selector that fires on random noise is worse than useless: it
 * manufactures confidence. The split-sample design plus a search-size correction
 * should hold the rate at or below alpha.
 *
 * Run: node test/simulate.js [trials]
 */

const { selectGroups } = require('../lib/analysis');
const { COLLECTION_DRAWS, ALPHA } = require('../lib/config');
const { mean, stdev } = require('../lib/stats');

function makeRng(seed) {
  // mulberry32 — small, fast, and reproducible so a surprising run can be replayed.
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function randomDraw(rng, startId, offset) {
  const pool = Array.from({ length: 80 }, (_, i) => i + 1);
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const minutes = 6 * 60 + offset * 4;
  const h = Math.floor(minutes / 60) % 12 || 12;
  return {
    draw_id: startId + offset,
    draw_time: `${h}:${String(minutes % 60).padStart(2, '0')} ${minutes >= 720 ? 'p.m.' : 'a.m.'}`,
    numbers: pool.slice(0, 20).sort((a, b) => a - b),
  };
}

function run(trials = 40, seed = 20240601) {
  const rng = makeRng(seed);
  let bonferroniHits = 0;
  let fdrHits = 0;
  const topCounts = [];
  const ratios = [];
  const timings = [];

  for (let t = 0; t < trials; t++) {
    const draws = Array.from({ length: COLLECTION_DRAWS }, (_, i) => randomDraw(rng, 9000000 + t * 1000, i));
    const { groups, diagnostics } = selectGroups(draws, { limit: 2 });
    if (groups.some((g) => g.passesBonferroni)) bonferroniHits++;
    if (groups.some((g) => g.passesFdr)) fdrHits++;
    if (groups[0]) topCounts.push(groups[0].outOfSampleCount);
    const level1 = diagnostics.chanceBenchmark?.[0];
    if (level1?.expectedIfRandom > 0) ratios.push(level1.observedCandidates / level1.expectedIfRandom);
    timings.push(diagnostics.elapsedMs);
  }

  const pct = (n) => `${((n / trials) * 100).toFixed(1)}%`;
  const report = {
    trials,
    alpha: ALPHA,
    falsePositiveRateBonferroni: pct(bonferroniHits),
    falsePositiveRateFdr: pct(fdrHits),
    meanTopOutOfSampleCount: +mean(topCounts).toFixed(2),
    maxTopOutOfSampleCount: Math.max(...topCounts),
    observedOverExpectedCandidates: {
      mean: +mean(ratios).toFixed(3),
      sd: +stdev(ratios).toFixed(3),
    },
    medianRuntimeMs: Math.round(mean(timings)),
    verdict: bonferroniHits / trials <= ALPHA
      ? 'PASS — the selector does not manufacture significance on random input'
      : 'FAIL — false-positive rate exceeds alpha',
  };

  console.log(JSON.stringify(report, null, 2));
  return report;
}

if (require.main === module) {
  const report = run(Number(process.argv[2]) || 40);
  process.exit(report.verdict.startsWith('PASS') ? 0 : 1);
}

module.exports = { run, makeRng, randomDraw };
